name: Generate PAC and ACL

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate files
        run: bun run generate

      - name: Check for changes
        run: |
          git add output/
          git diff --cached --quiet || echo "Changes detected, ready to commit

      - name: Commit and push changes
        if: success() && steps.check-for-changes.outputs.changed == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Auto-generate PAC and ACL files"
          git push
